# Beginner Python and Math for Data Science
## Lecture 15
### Linear Algebra - Fundamental Vector Spaces 

__Purpose:__ The purpose of this lecture is to understand fundamental vector spaces.

__At the end of this lecture you will be able to:__
> 1. Understand how fundamental vector spaces work.

In [1]:
import numpy as np 
from scipy import linalg 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
%matplotlib inline 

## 1.1 Fundamental Vector Spaces

### 1.1.1 Null Space:

__Overview:__ 
- The first "interesting"/"fundamental" vector space associated with any matrix $\pmb A$ is the Null Space
- __Null Space:__ The Null Space of a matrix $\pmb A \in \mathbb R^{m x n}$ consists of all the vectors that when multiplied with the matrix $\pmb A$ equal 0. In other words, it is a subspace that consists of all the possible solutions to the homogeneous equation $\pmb A \pmb x = \pmb 0$:<br>

<center> $N(A) = \{\pmb x \in \pmb R^n \mid \pmb A \pmb x = \pmb 0\}$ </center>

>> - If the column vectors in matrix $\pmb A$ are linearly independent, the only solution to $\pmb A \pmb x = \pmb 0$ is the trivial solution ($\pmb x = \pmb 0$) and therefore the Nullspace of A only contains the zero vector. This is due to the definition of linear independence 
>> - If the column vectors in matrix $\pmb A$ are linearly dependent, there exists another solution to $\pmb A \pmb x = \pmb 0$ other than the trivial solution ($\pmb x = \pmb 0$) and therefore the Nullspace of A contains additional vectors other than the zero vector. This is due to the definition of linear dependence 

__Helpful Points:__ 
1. To find the Null Space of a matrix, solve the equation $\pmb A \pmb x = \pmb 0$ using the Gaussian Elimination and RREF method we saw previously
2. In order for the solution set of vectors to the equation $\pmb A \pmb x = \pmb 0$ to form a subspace, it must satisfy the conditions outlined before (contain the zero vector, closed under multiplication and addition)

__Practice:__ Examples of Null Space in Python 

### Example 1 (Find Null Space):

If we want to find the Null Space of the matrix $\pmb A$, we have to solve the following equation 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    2 & 1 & 1\\
    1 & 2 & 3\\
    4 & 3 & 2
\end{bmatrix}
\begin{bmatrix}
    x_1\\
    x_2\\
    x_3
\end{bmatrix}
= 
\begin{bmatrix}
    0\\
    0\\
    0
\end{bmatrix}
\end{equation}

Since $\pmb x \in \mathbb R^3$, $N(A) = \{\pmb x \in \mathbb R^3 \mid \pmb A \pmb x = \pmb 0\}$

Which is the same as 
<center> $2x_1 + x_2 + x_3 = 0$ </center>
<center> $x_1 + 2x_2 + 3x_3 = 0$ </center>
<center> $4x_1 + 3x_2 + 2x_3 = 0$ </center>

We now know how to solve this system of equations used the Augmented Matrix:

\begin{equation}
\begin{array}{ccc|c}  
    2 & 1 & 1 & 0\\
    1 & 2 & 3 & 0\\
    4 & 3 & 2 & 0
\end{array}
\end{equation}  

In [2]:
A = np.array([[2,1,1],[1,2,3],[4,3,2]])
zero = np.zeros(3)
print(A)
print(zero)

[[2 1 1]
 [1 2 3]
 [4 3 2]]
[0. 0. 0.]


In [3]:
A_inv = linalg.inv(A)
print(A_inv)

[[ 1.  -0.2 -0.2]
 [-2.   0.   1. ]
 [ 1.   0.4 -0.6]]


In [4]:
linalg.solve(A, zero) 

array([0., 0., 0.])

The zero vector is the only vector inside the Null Space of $\pmb A$

### 1.1.2 Column Space:

__Overview:__ 
- The second "interesting"/"fundamental" vector space associated with any matrix $\pmb A$ is the Column Space
- __Column Space:__ The Column Space of a matrix $\pmb A \in \mathbb R^{m x n}$ consists of all the vectors that can be produced as linear combinations of the columns of the matrix $\pmb A$:
<center> $C(A) = \{\pmb b \in \mathbb R^m \mid \pmb b = \pmb A \pmb x$ for some $\pmb x \in \mathbb R^n\}$ </center>

>> - This formulation should make sense since we know the matrix-vector product is simply the multiplication of each column vector by the associated element of the vector:
\begin{equation}
\begin{bmatrix}
    \pmb A_1 & \pmb A_2 & \pmb A_3 & \dots & \pmb A_n
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2 \\
    x_3 \\
    \vdots \\
    x_n
\end{bmatrix}
=
\begin{bmatrix}
    x_1\pmb A_1 + x_2\pmb A_2 + x_3\pmb A_3 + \dots + x_n\pmb A_n
\end{bmatrix}
=
\pmb b
\end{equation}
<br>
>> - It is now intuitive to think of the solutions to our famous matrix equation $\pmb A \pmb x = \pmb b$ in terms of the column space of A. This equation will only have a solution if $\pmb b$ can be written as a linear combination of the column vectors in $\pmb A$, or we can say, this equation will only have a solution if $\pmb b$ is in the Column Space of $\pmb A$

__Helpful Points:__ 
1. Since the Column Space contains all the linear combinations of the column vectors of a matrix, we can also say that the Column Space is equal to the span of the column vectors: $C(A) = \langle S \rangle$ of the column vectors
2. To ensure the matrix-vector product is feasible, $\pmb b$ must have $m$ components and $\in \mathbb R^m$, whereas $\pmb x$ must have $n$ components and $\in \mathbb R^n$
3. In summary,
> - $\pmb A \pmb x = \pmb b$ has a solution if and only if $\pmb b \in C(A)$
> - $\pmb A \pmb x = \pmb b$ has no solution if and only if $\pmb b \notin C(A)$
4. The column vectors only form a basis of the Column Space if they are linearly independent. Also, if the column vectors are linearly independent, then the Null Space only contains the zero vector. In other words, if the Nulll Space contains more than just the zero vector, the column vectors do not form a basis for the Column Space. Once identifying the basis for the Column Space, we can easily describe the dimension of this space as simply the number of basis vectors

__Practice:__ Examples of Column Space in Python 

### Example 1 (b is in the Column Space of A):

\begin{equation}
\begin{array}{cc|c}  
    1 & 2 & 2\\
    2 & -4 & -12\\
\end{array}
\end{equation}  

In [25]:
A = np.array([[1,2],[2,-4]])
b = np.array([2,-12])
print(A)
print(b)

[[ 1  2]
 [ 2 -4]]
[  2 -12]


In [26]:
np.linalg.solve(A, b)

array([-2.,  2.])

The Column Space of A contains all the linear combination of the vectors $[1,2]^T$ and $[2,-4]^T$ and clearly there exists a set of coefficients $x_1=-2$ and $x_2=2$ to produce the vector $[2,-12]$. Therefore, this vector $\pmb b$ is in the Column Space of A. 

### Example 2 (b is not in the Column Space of A):

\begin{equation}
\begin{array}{cc|c}  
    1 & 2 & 3\\
    -2 & -4 & 8\\
\end{array}
\end{equation}  

In [13]:
A = np.array([[1,2],[-2,-4]])
b = np.array([3,8])
print(A)
print(b)

[[ 1  2]
 [-2 -4]]
[3 8]


In [14]:
np.linalg.solve(A, b)

LinAlgError: Singular matrix

The Column Space of A contains all the linear combination of the vectors $[1,-2]^T$ and $[2,-4]^T$ and clearly there does not exist any set of coefficients $x_1$ and $x_2$ to produce the vector $[3,8]$. Therefore, this vector $\pmb b$ is not in the Column Space of A. 

### Example 3 (Finding Basis and Dimension of the Column Space):

It turns out that by performing Gaussian Elimination on a matrix to obtain RREF, the result will provide insight into the basis and dimension of the Column Space. Let's see this below: 

If 
\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 0 & -1 & 0 & 4\\
    2 & 1 & 0 & 0 & 9\\
    -1 & 2 & 5 & 1 & -5\\
    1 & -1 & -3 & -2 & 9\\
\end{bmatrix}
\end{equation}

and we want to find the basis for the Column Space of A, we can begin by obtaining RREF of the matrix $\pmb A$:

\begin{equation}
\pmb R = rref(A) = 
\begin{bmatrix}
    1 & 0 & -1 & 0 & 4\\
    0 & 1 & 2 & 0 & 1\\
    0 & 0 & 0 & 1 & -3\\
    0 & 0 & 0 & 0 & 0\\
\end{bmatrix}
\end{equation}

The first, second, and fourth column are called __Pivot Columns__ since they have all non-zero entries with the except of the 1 entry. The three Pivot Columns are obviously linearly independent and by extension, it can also be proven that the associated columns in matrix $\pmb A$ are also linearly independent and span the Column Space. Therefore, the third and fifth column are "extra" columns and do not belong in the basis of the Column Space of A. 

In summary, to find the basis of the Column Space of A, obtain the RREF and find the Pivot Columns. The associated columns in the original matrix form the basis of the Column Space of A. Therefore, the dimension of this Column Space or the __Rank__ of the matrix $\pmb A$ is the number of basis vectors in the Column Space of A or the number of linearly independent vectors in the Column Space of $\pmb A$ or 3. 