# Exercises: Numpy Arrays

In [3]:
import numpy as np
print(np.__version__)

1.16.1


## Create a vector consisting of 10 zeros

In [4]:
Z = np.zeros(10)

## Set the 5th value to 5

In [5]:
Z[4] = 5

## Create a vector with values ranging from 37 to 84

In [7]:
X = np.arange(37, 85)
X

array([37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

## Reverse that vector

In [8]:
X = X[::-1]
X

array([84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68,
       67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51,
       50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37])

## Create a 4x4 matrix with values ranging from 43 to 58 

In [9]:
H = np.arange(43, 59).reshape(4,4)
H

array([[43, 44, 45, 46],
       [47, 48, 49, 50],
       [51, 52, 53, 54],
       [55, 56, 57, 58]])

## Find the indices of nonzero elements in [0, 2, 7, 0, 0, 8, 0]

In [10]:
nz = np.nonzero([0,2,7,0,0,8,0])
print(nz)

(array([1, 2, 5]),)


## Create a 3x3 identity matrix

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create a 2x4x3 array of random values

In [12]:
Z = np.random.random((2,4,3))
print(Z)

[[[0.81801248 0.11153374 0.39658704]
  [0.21413347 0.35989431 0.91161425]
  [0.79135524 0.8882107  0.881792  ]
  [0.07768981 0.11939659 0.78110727]]

 [[0.71907519 0.1986843  0.77067777]
  [0.08779466 0.76902188 0.10525641]
  [0.44315672 0.07129535 0.23867711]
  [0.93598401 0.49852021 0.93319085]]]


## Find the min, max, and mean values of that array

In [14]:
print(Z.min(), Z.max(), Z.mean())

0.07129535257481512 0.9359840105580294 0.5051108903767457


## Create a 7x7 array with 1's on the border and 0's inside

In [15]:
Z = np.ones((7,7))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## Add a border (filled with 0's) around that array
Hint: use the `pad()` method of the array.

In [16]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Normalize a 5x5 random matrix
That is, subtract the matrix mean from each value and then divide the result by the matrix standard deviation.

In [20]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.89354574  2.48023391 -0.857322    2.55674785 -0.91843146]
 [-0.42952541 -0.62867398  0.81698362 -0.55625608 -0.98819596]
 [-0.97061435  0.37977011 -0.4358983   1.10371756 -0.6173151 ]
 [-0.51093769  1.01393041 -1.01020583  0.59805294 -0.22950304]
 [-0.23121251 -0.90283352 -0.12864725 -0.85766989  0.43026021]]


## Multiply a 5x3 matrix of ones by a 3x2 matrix of twos
(i.e., take the dot product)

In [23]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))*2)
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))*2

[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]
[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


## Construct two arrays of 12 random integers from 0 to 9

In [30]:
Z1 = np.random.randint(0,10,12)
Z2 = np.random.randint(0,10,12)

## Find the common values between these two arrays
That is, values that appear in both arrays. They don't have to be in the same position.

In [32]:
print(np.intersect1d(Z1,Z2))

[0 1 8]


## Print the dates of yesterday, today, and tomorrow

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

## Create a vector of 10 sorted random values

In [35]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04841666 0.30194472 0.34476206 0.42200444 0.52012441 0.67836109
 0.84711678 0.87593273 0.89857459 0.95327518]


## Create random vector of size 10; replace the max value by 0
(Hint: use the `argmax` method.)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

# For more practice, 
check out this [100 numpy exercises (with solutions) repo on GitHub](https://github.com/rougier/numpy-100).