# Beginner Python and Math for Data Science
## Lecture 13
### Linear Algebra - Other Operations 

__Purpose:__ The purpose of this lecture is to expand our Linear Algebra knowledge to work with other matrix operations such as transpose, determinants and inverse.

__At the end of this lecture you will be able to:__
> 1. Understand the concepts of transpose, determinants and inverse 

In [1]:
import numpy as np 
from scipy import linalg 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
%matplotlib inline 

### 1.1.1 Other Operations with Matrices

### 1.1.1.1 Matrix Transpose

__Overview:__
- __[Matrix Transpose](https://en.wikipedia.org/wiki/Transpose):__ The transpose of a matrix is the mirror image of the matrix across the main diagonal of the matrix (upper left corner running down and to the right)
- We denote the transpose of a matrix $\pmb A$ as $\pmb A^T$ and is defined such that
<center> $(\pmb A^T)_{i,j} = A_{j,i}$ </center>
- For example:

\begin{equation}
\pmb A =
\begin{bmatrix}
    A_{11}       & A_{12}\\
    A_{21}       & A_{22}\\
    A_{31}       & A_{32}
\end{bmatrix}
\Rightarrow
\pmb A^T = 
\begin{bmatrix}
    A_{11} & A_{21} & A_{31}\\
    A_{12} & A_{22} & A_{32}
\end{bmatrix}
\end{equation}

__Helpful Points:__
1. There are some important rules with matrix transpose that we should remember:
> a. The transpose of a matrix product is the product of each matrix transpose $(\pmb A \pmb B)^T = \pmb B^T \pmb A^T$<br>
> b. The transpose of a matrix transpose is the original matrix $(\pmb A^T)^T = \pmb A$<br>
> c. The transpose of matrix addition is the addition of two matrix transpose $(\pmb A + \pmb B)^T = \pmb A^T + \pmb B^T$<br>
> d. The transpose of a scalar multiplication is multiplication of a scalar by the matrix transpose $(c\pmb A)^T = c\pmb A^T$<br>
> e. The dot product of two vectors is commutative $\pmb x^T \pmb y = (\pmb x^T \pmb y)^T = \pmb y^T \pmb x$ due to the properties above 
2. The definition of Square Matrices now should make sense since we understand what a matrix transpose is 

__Practice:__ Examples of Matrix Tranpose in Python 

### Example 1 (Matrix Transpose Examples):

### Example 1.1:

In [2]:
matrix_a = np.array([[1,0,1], [2,2,4], [5,6,2]])
print(matrix_a)

[[1 0 1]
 [2 2 4]
 [5 6 2]]


In [3]:
matrix_a.shape

(3, 3)

In [4]:
matrix_a.transpose()

array([[1, 2, 5],
       [0, 2, 6],
       [1, 4, 2]])

In [5]:
matrix_a.transpose().shape

(3, 3)

### Example 1.2:

In [6]:
matrix_b = np.array([[1,0], [2,2], [5,6]])
print(matrix_b)

[[1 0]
 [2 2]
 [5 6]]


In [7]:
matrix_b.shape

(3, 2)

In [8]:
matrix_b.transpose()

array([[1, 2, 5],
       [0, 2, 6]])

In [9]:
matrix_b.transpose().shape

(2, 3)

### Example 2 (Matrix Transpose Properties):

### Example 2.1 (Property 1):

In [10]:
np.dot(matrix_a, matrix_b).transpose()

array([[ 6, 26, 27],
       [ 6, 28, 24]])

In [11]:
np.dot(matrix_b.transpose(), matrix_a.transpose()) # same as above 

array([[ 6, 26, 27],
       [ 6, 28, 24]])

### Example 2.2 (Property 2):

In [12]:
matrix_a

array([[1, 0, 1],
       [2, 2, 4],
       [5, 6, 2]])

In [13]:
matrix_a.transpose().transpose() # same as above 

array([[1, 0, 1],
       [2, 2, 4],
       [5, 6, 2]])

### Problem 1

Create a matrix 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 2 & 4\\
    2 & 0 & 1\\
\end{bmatrix}
\end{equation}

and a matrix 

\begin{equation}
\pmb B = 
\begin{bmatrix}
    2 & 1 & 1\\
    2 & 3 & 1\\
\end{bmatrix}
\end{equation}

Try performing matrix multiplication on these two matrices. If you are unable to do so, explain why. Then modify one of the two matrices in a way that the two matrices can now be multiplied. 

In [ ]:
# write your code here 





### 1.1.1.2 Matrix Determinant:

__Overview:__ 
- __[Determinant](https://en.wikipedia.org/wiki/Determinant):__ The determinant of a square matrix is a value that is computed using the elements in the square matrix and is typically denoted as $det(A)$ or $\vert A \vert$
- The main purpose of a determinant is to check if a matrix is invertible or not (see below)
- It is possible to compute the determinant of any $n$ $x$ $n$ matrix:

> $2$ $x$ $2$ matrix:

\begin{equation}
det
\begin{bmatrix}
    A_{11}       & A_{12}\\
    A_{21}       & A_{22}
\end{bmatrix}
= A_{11}A_{22} - A_{12}A_{21}
\end{equation}

> $3$ $x$ $3$ matrix:

\begin{equation}
det
\begin{bmatrix}
    A_{11}       & A_{12} & A_{13}\\
    A_{21}       & A_{22} & A_{23}\\
    A_{31}       & A_{32} & A_{33}
\end{bmatrix}
= A_{11}
\begin{vmatrix}
    A_{22} & A_{23}\\
    A_{32} & A_{33}
\end{vmatrix}
- A_{12}
\begin{vmatrix}
    A_{21} & A_{23}\\
    A_{31} & A_{33}
\end{vmatrix}
+ A_{13}
\begin{vmatrix}
    A_{21} & A_{22}\\
    A_{31} & A_{32}
\end{vmatrix}
\end{equation}

__Helpful Points:__
1. In summary, if the $det(A) = 0$, then the matrix $\pmb A$ is not invertible. If $det(A) \neq 0$, then $\pmb A$ is invertible
2. There are two ways to calculate determinants:
> a. __Method 1:__ Using the formulas outlined above <br>
> b. __Method 2:__ Using NumPy and SciPy's built in matrix determinant methods: [`scipy.linalg.det`](https://docs.scipy.org/doc/scipy/reference/linalg.html) and [`numpy.linalg.det`](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.linalg.html)

__Practice:__ Examples of Matrix Determinant in Python 

### Example 1 (Determinant of 2x2 Matrix):

In [20]:
two_by_two = np.array([[1,2],[4,1]])
print(two_by_two)

[[1 2]
 [4 1]]


### Example 1.1 (Manual Calculation):

In [21]:
# my own function to calculate the determinant of a 2x2 matrix
def calc_det(arr):
    if arr.shape == (2,2): 
        return(arr[0,0]*arr[1,1] - arr[0,1]*arr[1,0])
    else:
        print("Not a 2 x 2 array")
        return

In [22]:
calc_det(two_by_two)

-7

### Example 1.2 (Programmatic Calculation):

In [23]:
linalg.det(two_by_two) # using scipy

-7.0

In [24]:
np.linalg.det(two_by_two) # using numpy

-6.999999999999999

### Example 2 (Determinant of 3x3 Matrix):

In [25]:
three_by_three = np.array([[1,2,1],[4,1,3],[3,2,1]])
print(three_by_three)

[[1 2 1]
 [4 1 3]
 [3 2 1]]


### Example 2.1 (Manual Calculation):

In [26]:
# function to get sub-block of an array
def get_sub(arr, row_list, col_list):
    rows = np.array(row_list, dtype = np.intp)
    columns = np.array(col_list, dtype = np.intp)
    sub = three_by_three[rows, columns]
    return(sub)

\begin{equation}
A_{11}
\begin{vmatrix}
    A_{22} & A_{23}\\
    A_{32} & A_{33}
\end{vmatrix}
\end{equation}

In [27]:
# get the block 
block_a = get_sub(three_by_three, [[1,1],[2,2]], [[1,2],[1,2]])
print(block_a)

[[1 3]
 [2 1]]


In [28]:
# calc det of block
part_a = three_by_three[0,0] * calc_det(block_a)
part_a

-5

\begin{equation}
-A_{12}
\begin{bmatrix}
    A_{21} & A_{23}\\
    A_{31} & A_{33}
\end{bmatrix}
\end{equation}

In [29]:
# get the block 
block_b = get_sub(three_by_three, [[1,1],[2,2]], [[0,2],[0,2]])
print(block_b)

[[4 3]
 [3 1]]


In [30]:
# calc det of block
part_b = -three_by_three[0,1] * calc_det(block_b)
part_b

10

\begin{equation}
A_{13}
\begin{bmatrix}
    A_{21} & A_{23}\\
    A_{31} & A_{32}
\end{bmatrix}
\end{equation}

In [31]:
# get the block 
block_c = get_sub(three_by_three, [[1,1],[2,2]], [[0,1],[0,1]])
print(block_c)

[[4 1]
 [3 2]]


In [32]:
# calc det of block
part_c = three_by_three[0,2] * calc_det(block_c)
part_c

5

\begin{equation}
A_{11}
\begin{bmatrix}
    A_{22} & A_{23}\\
    A_{32} & A_{33}
\end{bmatrix}
- A_{12}
\begin{bmatrix}
    A_{21} & A_{23}\\
    A_{31} & A_{33}
\end{bmatrix}
+ A_{13}
\begin{bmatrix}
    A_{21} & A_{22}\\
    A_{31} & A_{32}
\end{bmatrix}
\end{equation}

In [33]:
part_a + part_b + part_c

10

### Example 2.2 (Programmatic Calculation):

In [34]:
linalg.det(three_by_three) # using scipy

10.0

In [35]:
np.linalg.det(three_by_three) # using numpy

9.999999999999998

### Example 3 (Determinant of Non-Square Matrix):

In [36]:
new_matrix = np.array([[1,2],[3,4],[5,2],[4,4]])
print(new_matrix)

[[1 2]
 [3 4]
 [5 2]
 [4 4]]


In [37]:
linalg.det(new_matrix) # using scipy

ValueError: expected square matrix

In [38]:
np.linalg.det(new_matrix) # using numpy

LinAlgError: Last 2 dimensions of the array must be square

Notes:

- We can't compute the determinant of the above matrix since it is not square 
- Also, notice that the error messages in both SciPy and NumPy are different, suggesting that the functions actually have separate routines

### 1.1.1.3 Matrix Inverse

__Overview:__
- __[Inverse](https://en.wikipedia.org/wiki/Invertible_matrix):__ The inverse of a matrix is (somewhat) analagous to matrix division and is very useful for many linear algebra routines 
- The inverse of a matrix $\pmb A$ is such a matrix that returns the identity matrix when multiplied by $\pmb A$:
<center> ($\pmb A^{-1} \pmb A = \pmb I$) </center>
- It may not be immediately clear how matrix inverses are analgous to division, but recall that $X / Y$ is the same operation as multiplying X by the reciprocal of Y $\Rightarrow(1/Y)*X$. In the case of a matrix inverse, since X and Y refer to the same object, multiplying by its own reciprocal results in 1 $\Rightarrow (1/Y)*Y = 1$
- By definition, the inverse matrix $\pmb A^{-1}$ "undoes" the effects of the matrix $\pmb A$. We will take advantage of this fact in future sections

__Helpful Points:__
1. Be careful - a matrix inverse ($\pmb A^{-1}$) does not exist for every matrix. That is to say, there does not exist a matrix $\pmb B$, such that $\pmb B \pmb A = \pmb I$, for every matrix $\pmb A$. Instead, if the following 2 conditions hold, matrix $\pmb A$ is said to be __Invertible__, __Nonsingular__, or __Nondegenerate__ and there exists a matrix $\pmb B$ that will result in $\pmb A \pmb B = \pmb I$. Conversely, if an inverse does not exist for a matrix $\pmb A$, then the matrix is said to be __Singular__ or __Degenerate__.
> a. Matrix has to be square <br>
> b. Determinant of the matrix is non-zero
2. There are a few important properties regarding matrix inverses:
> a. If $\pmb A$ is a square matrix and has an inverse, then $\pmb A^{-1}$ is unique<br>
> b. If $\pmb A$ and $\pmb B$ are both invertible matrices, then $\pmb A \pmb B$ is also an invertible matrix and $(\pmb A \pmb B)^{-1} = \pmb B^{-1} \pmb A^{-1}$<br>
> c. If $\pmb A$ is an invertible matrix, then $\pmb A^T$ is also invertible and $(\pmb A^T)^{-1} = (\pmb A^{-1})^T$<br>
> d. If $\pmb A$ is an invertible matrix and $\alpha$ is a nonzero scalar, then $(\alpha \pmb A)^{-1} = \frac{1}
{\alpha}\pmb A^{-1}$<br>
> e. $\pmb A^{-1} \pmb A = \pmb I$ is true and $\pmb A \pmb A^{-1} = \pmb I$ is also true
3. There are a few ways to calculate a matrix inverse if it exists:
> a. __Method 1:__ Using the determinant and the __[adjugate](https://en.wikipedia.org/wiki/Adjugate_matrix)__ of the matrix $\pmb A$<br>
> b. __Method 2:__ Using matrix row operations <br>
> c. __Method 3:__ Using NumPy and SciPy's built in matrix inverse methods: [`scipy.linalg.inv`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.inv.html#scipy.linalg.inv) and [`numpy.linalg.inv`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv)
4. The most useful ability of matrix inverses is so to solve linear equations such as $\pmb A \pmb x = \pmb b$ 

__Practice:__ Examples of Matrix Inverse in Python 

### Example 1 (Calculating Inverses):

In [39]:
A = np.array([[1,1], [2,3]])
print(A)

[[1 1]
 [2 3]]


### Example 1.1 (Using Method 1):

We can calculate the inverse of a $2$ $x$ $2$ matrix using the determinant and the adjugate of the matrix. Technically speaking, the adjugate of a matrix is the transpose of the cofactor of the matrix and this can get fairly complicated for matrices larger than $2$ $x$ $2$. Therefore, we will illustrate the formula for a $2$ $x$ $2$ matrix and propose this method as a viable method only for matrices of this shape. For larger matrices, methods 2 and 3 will prevail. 

If
\begin{equation}
A = 
\begin{bmatrix}
    A_{11} & A_{12}\\
    A_{12} & A_{22}
\end{bmatrix}
\end{equation}

Then
\begin{equation}
A^{-1} = \frac{1}{det(A)}
adj(A)
\end{equation}
where
\begin{equation}
adj(A) = 
\begin{bmatrix}
    A_{22} & -A_{12}\\
    -A_{21} & A_{11}
\end{bmatrix}
\end{equation}

In [40]:
adj_A = np.array([[3,-1],[-2,1]])
adj_A

array([[ 3, -1],
       [-2,  1]])

In [41]:
(1/np.linalg.det(A)) * adj_A

array([[ 3., -1.],
       [-2.,  1.]])

### Example 1.2 (Using Method 2):

You have to wait for a future section to see this...

### Example 1.3 (Using Method 3):

In [42]:
linalg.inv(A) # using scipy

array([[ 3., -1.],
       [-2.,  1.]])

In [43]:
np.linalg.inv(A) # using numpy

array([[ 3., -1.],
       [-2.,  1.]])

### Example 2 (Checking if Inverse Exists):

### Example 2.1 (Square Matrix that is Non-Singular):

In [44]:
A = np.array([[1,1,4], [2,3,1], [3,3,2]])
print(A)

[[1 1 4]
 [2 3 1]
 [3 3 2]]


In [45]:
linalg.det(A)

-10.0

In [46]:
linalg.inv(A) 

array([[-3.00000000e-01, -1.00000000e+00,  1.10000000e+00],
       [ 1.00000000e-01,  1.00000000e+00, -7.00000000e-01],
       [ 3.00000000e-01, -1.66533454e-17, -1.00000000e-01]])

In [47]:
np.linalg.inv(A)

array([[-0.3, -1. ,  1.1],
       [ 0.1,  1. , -0.7],
       [ 0.3,  0. , -0.1]])

### Example 2.2 (Square Matrix that is Singular):

In [48]:
B = np.array([[1,2], [2,4]])
print(B)

[[1 2]
 [2 4]]


In [49]:
linalg.inv(B) # using scipy 

LinAlgError: singular matrix

In [50]:
np.linalg.inv(B) # using numpy 

LinAlgError: Singular matrix

Why is this matrix singular? It is square, but its determinant is equal to 0 and we know that invertible matrices must have a non-zero determinant. See below:

In [51]:
linalg.det(B)

0.0

In [52]:
np.linalg.det(B)

0.0

### Example 3 (Checking Matrix Properties):

In [53]:
A = np.array([[1,2,4],[2,1,0],[1,1,5]])
print(A)

[[1 2 4]
 [2 1 0]
 [1 1 5]]


In [54]:
B = np.array([[3,0,0],[4,1,0],[2,3,5]])
print(B)

[[3 0 0]
 [4 1 0]
 [2 3 5]]


### Example 3.1 ($AA^{-1}$ = I)

In [55]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.45454545  0.54545455  0.36363636]
 [ 0.90909091 -0.09090909 -0.72727273]
 [-0.09090909 -0.09090909  0.27272727]]


In [56]:
np.dot(A, A_inv) # identity matrix 

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-17, -2.77555756e-17,  1.00000000e+00]])

### Example 3.2 ($A^{-1}$A = I)

In [57]:
np.dot(A_inv, A) # identity matrix 

array([[ 1.00000000e+00,  5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

### Example 3.3 ( $(AB)^{-1} = B^{-1}A^{-1}$ )

In [58]:
np.linalg.inv(np.dot(A, B)) 

array([[-0.15151515,  0.18181818,  0.12121212],
       [ 1.51515152, -0.81818182, -1.21212121],
       [-0.86666667,  0.4       ,  0.73333333]])

In [59]:
np.dot(np.linalg.inv(B), np.linalg.inv(A))

array([[-0.15151515,  0.18181818,  0.12121212],
       [ 1.51515152, -0.81818182, -1.21212121],
       [-0.86666667,  0.4       ,  0.73333333]])

### Example 3.4 ($ (A^T)^{-1} = (A^{-1})^T$ )

In [60]:
np.linalg.inv(A.transpose()) 

array([[-0.45454545,  0.90909091, -0.09090909],
       [ 0.54545455, -0.09090909, -0.09090909],
       [ 0.36363636, -0.72727273,  0.27272727]])

In [61]:
np.linalg.inv(A).transpose()

array([[-0.45454545,  0.90909091, -0.09090909],
       [ 0.54545455, -0.09090909, -0.09090909],
       [ 0.36363636, -0.72727273,  0.27272727]])

### Problem 2

Create a matrix 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 2\\
    2 & 0\\
\end{bmatrix}
\end{equation}

Calculate the determinant and inverse of this matrix. Use any method(s) you please, but ensure one of those methods is the manual calculation. 

In [ ]:
# write your code here 





### SOLUTIONS

### Problem 1

Create a matrix 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 2 & 4\\
    2 & 0 & 1\\
\end{bmatrix}
\end{equation}

and a matrix 

\begin{equation}
\pmb B = 
\begin{bmatrix}
    2 & 1 & 1\\
    2 & 3 & 1\\
\end{bmatrix}
\end{equation}

Try performing matrix multiplication on these two matrices. If you are unable to do so, explain why. Then modify one of the two matrices in a way that the two matrices can now be multiplied. 

In [14]:
A = np.array([[1,2,4],[2,0,1]])
B = np.array([[2,1,1],[2,3,1]])
print(A)
print(B)

[[1 2 4]
 [2 0 1]]
[[2 1 1]
 [2 3 1]]


In [15]:
np.dot(A,B)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
A_transpose = A.transpose()
print(A_transpose)

[[1 2]
 [2 0]
 [4 1]]


In [17]:
np.dot(A_transpose, B)

array([[ 6,  7,  3],
       [ 4,  2,  2],
       [10,  7,  5]])

or you can transpose B

In [18]:
B_transpose = B.transpose()
print(B_transpose)

[[2 2]
 [1 3]
 [1 1]]


In [19]:
np.dot(A, B_transpose)

array([[ 8, 12],
       [ 5,  5]])

### Problem 2

Create a matrix 

\begin{equation}
\pmb A = 
\begin{bmatrix}
    1 & 2\\
    2 & 0\\
\end{bmatrix}
\end{equation}

Calculate the determinant and inverse of this matrix. Use any method(s) you please, but ensure one of those methods is the manual calculation. 

In [62]:
A = np.array([[1,2],[2,0]])
print(A)

[[1 2]
 [2 0]]


In [63]:
np.linalg.det(A)

-4.0

In [64]:
np.linalg.inv(A)

array([[ 0.  ,  0.5 ],
       [ 0.5 , -0.25]])