# Beginner Python and Math for Data Science
## Lecture 9
### Linear Algebra - Matrices

__Purpose:__ The purpose of this lecture is to expand our Linear Algebra knowledge to work with matrices.

__At the end of this lecture you will be able to:__
> 1. Understand what matrices are.

In [1]:
import numpy as np 
from scipy import linalg 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d
%matplotlib inline 

## 1.1 Matrices 

### 1.1 What is a Matrix?

__Overview:__
- __[Matrix](https://en.wikipedia.org/wiki/Matrix_(mathematics)):__ A Matrix is simply a two-dimensional array that consists of numbers along the rows and columns 
- Typically, we characterize matrices by their shape: an $m$ $x$ $n$ matrix $\pmb A$ is said to have $m$ rows and $n$ columns
- Each element in the matrix is denoted with `i` and `j` notation in the form of $a_{i,j}$ where $i$ represents the row index and $j$ represents the column index 
- You will notice that the "rows" or "columns" in a matrix are just vectors as we have seen so far

__Helpful Points:__
1. In Python, matrices are considered two-dimensional arrays and are of the type `numpy.ndarray`
2. There are some "special" matrices such as:
>a. An __[Identity Matrix](https://en.wikipedia.org/wiki/Identity_matrix)__ is a matrix that has ones along the main diagonal and zeors everywhere else <br>
>b. A __Zero Matrix__ is a matrix with zeros on every element of the matrix <br>
>c. A __[Square Matrix](https://en.wikipedia.org/wiki/Square_matrix)__ is a matrix with equal number of rows as columns <br>
>d. A __[Symmetric Matrix](https://en.wikipedia.org/wiki/Symmetric_matrix)__ is a matrix that can be flipped (transposed) without affecting the elements of the matrix <br>
>e. A __[Diagonal Matrix](https://en.wikipedia.org/wiki/Diagonal_matrix)__ is a matrix the main diagonal has non-zero elements from the upper left to the lower right and the remaining elements are zero<br>

__Practice:__ Examples of matrices in Python 

### Example 1 (Create Square Matrix):

In [2]:
my_matrix = np.array([[1,2], [3,4]])
print(my_matrix)

[[1 2]
 [3 4]]


In [3]:
my_matrix.ndim

2

In [4]:
my_matrix.shape

(2, 2)

The matrix above is square because there are equal rows and columns. 

### Example 2 (Create Non-Square Matrix):

In [11]:
my_matrix_1 = np.array([[1,2], [4,5], [7,8]])
print(my_matrix_1)

[[1 2]
 [4 5]
 [7 8]]


In [12]:
my_matrix_1.ndim

2

In [13]:
my_matrix_1.shape

(3, 2)

The matrix above is not square because there are unequal rows and columns. 

### Example 3 (Identity Matrix):

In [14]:
identity_matrix = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Example 4 (Symmetric Matrix):

In [15]:
symmetric_matrix = np.array([[1,2,1], [2,0,1], [1,1,1]])
print(symmetric_matrix)

[[1 2 1]
 [2 0 1]
 [1 1 1]]


In [16]:
print(symmetric_matrix.transpose()) # flip the matrix 

[[1 2 1]
 [2 0 1]
 [1 1 1]]


The original matrix was considered symmetric since after flipping the matrix (i.e. turning it on its side), the elements of the matrix do not change. 

### Example 5 (Diagonal Matrix):

In [17]:
diagonal_matrix = np.array([[1,0,0], [0,4,0], [0,0,-3], [0,0,0]])
print(diagonal_matrix)

[[ 1  0  0]
 [ 0  4  0]
 [ 0  0 -3]
 [ 0  0  0]]


In general, a matrix is considered diagonal if for any i,j combination, where i = j, the element must be non-zero. For any other element, it is set to zero 

### Example 6 (Zero Matrix):

In [18]:
zero_matrix = np.zeros(9).reshape(3,3)
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 1.2 Notating Matrices:

__Overview:__
- Again, it is useful to know how matrices are notated in mathematical notation 
- Here are some practices used when notating matrices:
> 1. The matrix name is usually uppercase (so $\pmb X$ would represent a matrix)
> 2. The matrix name is usually boldfaced ($\pmb X$)
> 3. The elements within a matrix are italicized and referenced with subscripts denoting their ordered position ($\textit A_{m,n}$)

- As mentioned above, matrices are just two-dimensional arrays where each row and column are vectors: 
<img src="img35.png">
- Row vectors:
> $[A_{1,1},A_{1,2}]$ and $[A_{2,1},A_{2,2}]$
- Columns vectors:
> $[A_{1,1},A_{2,1}]^T$ and $[A_{1,2},A_{2,2}]^T$

__Helpful Points:__
1. Similar to vectors, we can specify the real coordinate space that the matrix belongs to. If a real-valued matrix $\pmb A$ has $m$ rows and $n$ columns, then we can say that $\pmb A \in \mathbb R^{m x n}$
2. Matrix notation allows us to access specific elements within the matrix by row/column indexing similar to lists and other objects in Python 

__Practice:__ Examples of Accessing Matrices in Python 

### Example 1 (Accessing Elements in Matrices):

In [19]:
my_matrix = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(my_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
my_matrix[:,2:3] # 3rd column, all rows 

array([[ 3],
       [ 6],
       [ 9],
       [12]])

This is known as a Column Vector

In [21]:
my_matrix[0,:] # first row, all columns

array([1, 2, 3])

This is known as a Row Vector

In [22]:
my_matrix[2,2] # 3rd row,3rd column

9